[package]
name = "hug-reminder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
lettre = "0.10.0-rc.7"

[dependencies.clap]
version = "3.2.3"
features = ["default", "wrap_help"]
